server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
      - id: product_route
        uri: lb://service-product
        predicates:
        - Path=/admin/product/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许跨域的服务器
            allowedMethods: "*"
