server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
      - id: product_route
        uri: lb://service-product
        predicates:
        - Path=/admin/product/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #允许所有来源访问
            allowedMethods: "*"  #允许所有请求方式跨域访问
            allowedHeaders: "*"  #允许任意请求头跨域
            allowCredentials: true #允许Cookie等一些安全标识头跨域
